<?php
$translate = $this->plugin('translate');
$prevText = $translate('Prev: ');
$nextText = $translate('Next: ');
$default_thumb = $this->assetUrl('img/BlockI-Logo-Full-Color-RGB.png');
?>


<?php if ($prevPage || $nextPage): ?>

    <div class="site-page-pagination">

        <div class="prev-page">
            <?php if ($prevPage){
                $prevTitle = $prevPage->title();
                $prevPageThumb = getThumbnail($prevPage, $default_thumb);
                echo $this->hyperlink($prevText . $prevTitle, $prevPage->siteUrl());
                echo '<img src="' . $prevPageThumb['url'] . '" alt="'. $prevPageThumb['alt'].'">';
            }?>
        </div>

        <div class="next-page">
            <?php  if ($nextPage){
                $nextTitle = $nextPage->title();
                $nextPageThumb = getThumbnail($nextPage, $default_thumb);
                echo $this->hyperlink($nextText . $nextTitle, $nextPage->siteUrl());
                echo '<img src="' . $nextPageThumb['url'] . '" alt="' .$nextPageThumb['alt'].'">';
            }?>
        </div>
    </div>
<?php endif; ?>