<?php
$translate = $this->plugin('translate');
$prevText = $translate('Previous Section: ');
$nextText = $translate('Next Section: ');
$default_thumb = $this->assetUrl('img/BlockI-Logo-Full-Color-RGB.png');
function getThumbnail($page, $default){
    //default thumbnail if the page has no media
    $url = $default;
    $alt = 'Default image for next page when no specific media was found for the page';

    //get the first media attachment on the target page
    foreach($page->blocks() as $block){
        if (get_class($block) === 'Omeka\Api\Representation\SitePageBlockRepresentation'){
            if ($block->attachments()){
                $media = $block->attachments()[0]->media();
                $url = $media->thumbnailUrl("square");

                if (array_key_exists('o-module-alt-text:alt-text', $media->primaryMedia()->jsonSerialize())
                    && $media->primaryMedia()->jsonSerialize()['o-module-alt-text:alt-text']
                ) {
                    $alt = $media->primaryMedia()->jsonSerialize()['o-module-alt-text:alt-text'];
                } else {
                    $alt = 'Thumbnail preview for next page';
                }

                break;
            }
        }
    }
    return ['url' => $url, 'alt' => $alt];
}
?>


<?php if ($prevPage || $nextPage): ?>

    <div class="site-page-pagination">

        <div class="container">
            <div class="row justify-content-between">
            <?php if ($prevPage){
                $prevTitle = $prevPage->title();
                $prevPageThumb = getThumbnail($prevPage, $default_thumb);?>
                <div class="mr-auto">
                    <div class="card nav-card" >
                    <div class="row">
                        <div class="col-auto">
                            <a  href="<?php echo $prevPage->siteUrl() ?>" class="stretched-link">
                            <img src="<?php echo $prevPageThumb['url'] ?>"
                                 class="img-fluid .img-thumbnail"
                                 alt="<?php echo $prevPageThumb['alt'] ?>"
                                 style="max-width: 100px"
                            >
                            </a>
                        </div>
                        <div class="col">
                            <div class="card-block px-2">
                                <a class="stretched-link" href="<?php echo $prevPage->siteUrl() ?>"><?php echo $prevText ?></a>
                                <h4 class="card-title"><?php echo $prevTitle ?></h4>
                            </div>
                        </div>
                    </div>
                </div>
                </div>
            <?php }?>
            <?php if ($nextPage){
                $nextTitle = $nextPage->title();
                $nextPageThumb = getThumbnail($nextPage, $default_thumb);?>
                <div class="ml-auto">
                    <div class="card nav-card" >
                        <div class="row">
                            <div class="col-auto">
                                <a  href="<?php echo $nextPage->siteUrl() ?>" class="stretched-link">
                                    <img src="<?php echo $nextPageThumb['url'] ?>"
                                         class="img-fluid .img-thumbnail"
                                         alt="<?php echo $nextPageThumb['alt'] ?>"
                                         style="max-width: 100px"
                                    >
                                </a>
                            </div>
                            <div class="col">
                                <div class="card-block px-2">
                                    <a class="stretched-link" href="<?php echo $nextPage->siteUrl() ?>"><?php echo $nextText ?></a>
                                    <h4 class="card-title"><?php echo $nextTitle ?></h4>
                                </div>
                            </div>
                        </div>
                    </div>
                <div>
            <?php }?>
            </div>
        </div>
    </div>
<?php endif; ?>