<?php
$translate = $this->plugin('translate');
$prevText = $translate('Previous Section: ');
$nextText = $translate('Next Section: ');
$default_thumb = $this->assetUrl('img/Placeholder.png');
?>


<?php if ($prevPage || $nextPage): ?>

    <div class="site-page-pagination">

        <div class="container">
            <div class="row justify-content-between">
            <?php if ($prevPage){
                $prevTitle = $prevPage->title();
                $prevPageThumb = getThumbnail($prevPage, $default_thumb, 'square');?>
                <div class="mr-auto">
                    <div class="card nav-card" >
                    <div class="row">
                        <div class="col-auto">
                            <a  href="<?php echo $prevPage->siteUrl() ?>" class="stretched-link">
                            <img src="<?php echo $prevPageThumb['url'] ?>"
                                 class="img-fluid .img-thumbnail"
                                 alt="<?php echo $prevPageThumb['alt'] ?>"
                                 style="max-width: 100px"
                            >
                            </a>
                        </div>
                        <div class="col">
                            <div class="card-block px-2">
                                <a class="stretched-link" href="<?php echo $prevPage->siteUrl() ?>"><?php echo $prevText ?></a>
                                <h4 class="card-title"><?php echo $prevTitle ?></h4>
                            </div>
                        </div>
                    </div>
                </div>
                </div>
            <?php }?>
            <?php if ($nextPage){
                $nextTitle = $nextPage->title();
                $nextPageThumb = getThumbnail($nextPage, $default_thumb, 'square');?>
                <div class="ml-auto">
                    <div class="card nav-card" >
                        <div class="row">
                            <div class="col-auto">
                                <a  href="<?php echo $nextPage->siteUrl() ?>" class="stretched-link">
                                    <img src="<?php echo $nextPageThumb['url'] ?>"
                                         class="img-fluid .img-thumbnail"
                                         alt="<?php echo $nextPageThumb['alt'] ?>"
                                         style="max-width: 100px"
                                    >
                                </a>
                            </div>
                            <div class="col">
                                <div class="card-block px-2">
                                    <a class="stretched-link" href="<?php echo $nextPage->siteUrl() ?>"><?php echo $nextText ?></a>
                                    <h4 class="card-title"><?php echo $nextTitle ?></h4>
                                </div>
                            </div>
                        </div>
                    </div>
                <div>
            <?php }?>
            </div>
        </div>
    </div>
<?php endif; ?>