<div class="row">
<?php
$layouts = [];
$blocks = $page->blocks();
$toc_block = array_filter($blocks, function($var) { return $var->layout() =='tableOfContents'; });
if(count($toc_block)) :  // if there is a table of contents block ?>
	<div class="col-md-3">
		<?php 
		$toc_block = array_values($toc_block);
		$this->blockLayout()->prepareRender($toc_block[0]->layout()); 
		echo $this->blockLayout()->render($toc_block[0]);
		?>
	</div>
	<div class="col-md-9">
<?php else: ?>
	<div class="col-sm-12">
<?php endif; ?>
<?php
foreach ($blocks as $block) {
	if(strcmp ($block->layout(), "tableOfContents")) { // if not table of contents block
		if (!array_key_exists($block->layout(), $layouts)) {
			// Prepare render only once per layout type.
			$layouts[$block->layout()] = null;
			$this->blockLayout()->prepareRender($block->layout());
		} ?>
		<div class="block <?php echo $block->layout();?>-block">
		<?php
		echo $this->blockLayout()->render($block); ?>
		</div>
<?php
	}
}
?>
</div>