<div class="row">
	<?php $layouts = []; ?>
	<div class="col-md-3">
	<?php echo $site->publicNav()->menu()->renderMenu(null, [
		'maxDepth' => $this->themeSetting('nav_depth') - 1
	]);?>
	</div>
	<div class="col-md-9">
	<?php
	foreach ($page->blocks() as $block) {
		if (!array_key_exists($block->layout(), $layouts)) {
			// Prepare render only once per layout type.
			$layouts[$block->layout()] = null;
			$this->blockLayout()->prepareRender($block->layout());
		} ?>
		<div class="block <?php echo $block->layout();?>-block">
		<?php
		echo $this->blockLayout()->render($block); ?>
		</div>
	<?php
	}
	?>
</div>